"""Question classifier for PM interviews.

Classifies generated questions as PM-answerable (planning), DEV-only
(development/technical), or decide-later (premature/unknowable).

DEV-only questions are reframed into PM-friendly language or returned to
the user with the option to defer to the development interview phase.
Decide-later questions are returned to the user with the option to defer
rather than being automatically skipped.

Uses the configured clarification model for accurate judgment and reframing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
import json
import re

import structlog

from ouroboros.config import get_clarification_model
from ouroboros.core.errors import ProviderError
from ouroboros.core.types import Result
from ouroboros.providers.base import (
    CompletionConfig,
    LLMAdapter,
    Message,
    MessageRole,
)

log = structlog.get_logger()
_CLASSIFIER_TEMPERATURE = 0.2

# Default placeholder when LLM doesn't provide one for decide-later
_DEFAULT_PLACEHOLDER = "To be determined in a later phase once more information is available."


class QuestionCategory(StrEnum):
    """Category of a question in the PM interview context."""

    PLANNING = "planning"
    DEVELOPMENT = "development"
    DECIDE_LATER = "decide_later"


class ClassifierOutputType(StrEnum):
    """Output type of the classifier — determines how the question is handled.

    PASSTHROUGH: Planning question forwarded unchanged to the PM.
    REFRAMED: Development question rewritten in PM-friendly language.
    DEFERRED: Deeply technical question returned to user with defer option.
    DECIDE_LATER: Premature question returned to user with decide-later option.
    """

    PASSTHROUGH = "passthrough"
    REFRAMED = "reframed"
    DEFERRED = "deferred"
    DECIDE_LATER = "decide_later"


@dataclass(frozen=True, slots=True)
class ClassificationResult:
    """Result of classifying a question.

    Attributes:
        original_question: The question as generated by the interview engine.
        category: Whether the question is planning, development, or decide-later.
        reframed_question: PM-friendly version if reframing was needed.
            Same as original if already PM-friendly.
        reasoning: Why the classifier chose this category.
        defer_to_dev: Whether this question should be deferred entirely.
        decide_later: Whether this question is premature and should be
            returned to the user with the option to defer.
        placeholder_response: Placeholder response for decide-later questions
            (used if the user chooses to defer).
    """

    original_question: str
    category: QuestionCategory
    reframed_question: str
    reasoning: str
    defer_to_dev: bool = False
    decide_later: bool = False
    placeholder_response: str = ""

    @property
    def output_type(self) -> ClassifierOutputType:
        """Determine the classifier output type for this result.

        Returns:
            DECIDE_LATER if premature/unknowable question (returned to user
                with option to defer),
            DEFERRED if deeply technical (returned to user with option to
                defer to dev phase),
            PASSTHROUGH if planning question (forwarded unchanged),
            REFRAMED if development question rewritten for PM.
        """
        if self.decide_later:
            return ClassifierOutputType.DECIDE_LATER
        if self.defer_to_dev:
            return ClassifierOutputType.DEFERRED
        if self.category == QuestionCategory.PLANNING:
            return ClassifierOutputType.PASSTHROUGH
        return ClassifierOutputType.REFRAMED

    @property
    def question_for_pm(self) -> str:
        """The question to present to the PM.

        For PASSTHROUGH: returns original_question unchanged.
        For REFRAMED: returns the reframed_question.
        For DEFERRED: returns original_question (shown to user
            so they can choose to answer or defer to dev).
        For DECIDE_LATER: returns original_question (shown to user
            so they can choose to answer or defer).
        """
        if self.output_type == ClassifierOutputType.PASSTHROUGH:
            return self.original_question
        if self.output_type == ClassifierOutputType.REFRAMED:
            return self.reframed_question
        if self.output_type in (
            ClassifierOutputType.DECIDE_LATER,
            ClassifierOutputType.DEFERRED,
        ):
            return self.original_question
        return ""


_CLASSIFICATION_SYSTEM_PROMPT = """\
You are a question classifier for a Product Requirements Document (PM) interview.

Your job is to determine whether a question generated during a requirements interview
is answerable by a Product Manager (PM), requires deep technical/development expertise,
or is premature and should be deferred to a later stage.

## Categories

**PLANNING** — PM can answer directly:
- Business goals, user needs, market context
- Success metrics, KPIs, acceptance criteria
- Priority, timeline, budget constraints
- User stories, personas, workflows
- Scope decisions (in/out), feature prioritization
- Compliance, regulatory, legal requirements

**DEVELOPMENT** — Requires technical expertise:
- Architecture decisions (microservices vs monolith, database choice)
- Implementation details (algorithms, data structures, APIs)
- Infrastructure (hosting, CI/CD, deployment strategy)
- Code-level patterns (design patterns, frameworks)
- Performance optimization specifics
- Security implementation details

**DECIDE_LATER** — Premature or unknowable at this stage:
- Questions whose answer depends on decisions not yet made
- Future-phase concerns (post-MVP optimization, scaling details)
- Questions requiring user research or data that doesn't exist yet
- Speculative trade-offs that can't be resolved without prototyping
- Cross-cutting concerns that will become clearer as other requirements solidify

## Rules

1. If the question is PLANNING → return it unchanged
2. If the question is DEVELOPMENT but can be reframed for a PM → provide a reframed version
   - Reframing means asking about the *business need* behind the technical question
   - Example: "Which database should we use?" → "What are your data storage needs — \
how much data, how fast does it need to be accessed, and do you need real-time updates?"
3. If the question is deeply technical with no PM-friendly reframe → mark as defer_to_dev=true
4. If the question is premature or unknowable right now → mark as decide_later=true and \
provide a placeholder_response that acknowledges the question and explains why it is deferred

## Response Format

Respond ONLY with valid JSON:
{"category": "planning"|"development"|"decide_later", "reframed_question": "...", \
"reasoning": "...", "defer_to_dev": false|true, "decide_later": false|true, \
"placeholder_response": "..."}

When decide_later=true, placeholder_response MUST contain a brief, professional \
acknowledgment such as: "This will be determined after [prerequisite]. \
Marking as a decision point for later."
"""


@dataclass
class QuestionClassifier:
    """Classifies interview questions as PM-answerable, DEV-only, or decide-later.

    Uses the configured clarification model to judge whether questions are
    appropriate for a PM audience, reframes technical questions when possible,
    and identifies premature questions that should be returned to the user
    with the option to defer.

    Attributes:
        llm_adapter: LLM adapter for classification calls.
        model: Explicit model override for classification calls.
        temperature: Low temperature for consistent classification.
        codebase_context: Shared codebase exploration context for informed classification.
    """

    llm_adapter: LLMAdapter
    model: str | None = None
    implicit_model: str | None = None
    model_is_explicit: bool = field(default=False, init=False)
    temperature: float = _CLASSIFIER_TEMPERATURE
    codebase_context: str = ""

    def __post_init__(self) -> None:
        """Resolve implicit default model while preserving explicit caller pins."""
        self.model_is_explicit = self.model is not None
        if self.model is None:
            self.model = self.implicit_model or get_clarification_model()

    async def classify(
        self,
        question: str,
        interview_context: str = "",
    ) -> Result[ClassificationResult, ProviderError]:
        """Classify a question and optionally reframe it for PM audience.

        Args:
            question: The question to classify.
            interview_context: Optional conversation context for better judgment.

        Returns:
            Result containing ClassificationResult or ProviderError.
        """
        user_content_parts = [f"Question to classify:\n{question}"]

        if interview_context:
            user_content_parts.append(f"\nInterview context so far:\n{interview_context}")

        if self.codebase_context:
            user_content_parts.append(
                f"\nCodebase context (brownfield):\n{self.codebase_context[:2000]}"
            )

        messages = [
            Message(role=MessageRole.SYSTEM, content=_CLASSIFICATION_SYSTEM_PROMPT),
            Message(role=MessageRole.USER, content="\n".join(user_content_parts)),
        ]

        assert self.model is not None
        config = CompletionConfig(
            model=self.model,
            role="question_classification",
            model_is_explicit=self.model_is_explicit,
            temperature=self.temperature,
            max_tokens=512,
        )

        result = await self.llm_adapter.complete(messages, config)

        if result.is_err:
            log.warning(
                "classifier.llm_failed",
                error=str(result.error),
            )
            return Result.err(result.error)

        try:
            parsed = self._parse_response(result.value.content, question)
            log.info(
                "classifier.classified",
                category=parsed.category,
                defer_to_dev=parsed.defer_to_dev,
                decide_later=parsed.decide_later,
                output_type=parsed.output_type,
            )
            return Result.ok(parsed)
        except (ValueError, KeyError) as e:
            log.warning(
                "classifier.parse_failed",
                error=str(e),
                response=result.value.content[:200],
            )
            # Fallback: treat as planning (safe default — PM gets to answer)
            return Result.ok(
                ClassificationResult(
                    original_question=question,
                    category=QuestionCategory.PLANNING,
                    reframed_question=question,
                    reasoning="Classification parse failed; defaulting to planning.",
                )
            )

    def _parse_response(
        self,
        response: str,
        original_question: str,
    ) -> ClassificationResult:
        """Parse LLM classification response.

        Args:
            response: Raw LLM response text.
            original_question: The original question for reference.

        Returns:
            Parsed ClassificationResult.

        Raises:
            ValueError: If response cannot be parsed.
        """
        text = response.strip()

        # Extract JSON from markdown code blocks if present
        json_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
        if json_match:
            text = json_match.group(1)
        else:
            json_match = re.search(r"\{.*\}", text, re.DOTALL)
            if json_match:
                text = json_match.group(0)

        data = json.loads(text)

        category_str = data.get("category", "planning").lower()
        if category_str == "decide_later":
            category = QuestionCategory.DECIDE_LATER
        elif category_str == "development":
            category = QuestionCategory.DEVELOPMENT
        else:
            category = QuestionCategory.PLANNING

        reframed = data.get("reframed_question", original_question)
        if not reframed or not reframed.strip():
            reframed = original_question

        is_decide_later = bool(data.get("decide_later", False))
        placeholder = data.get("placeholder_response", "")

        # Ensure decide-later always has a placeholder
        if is_decide_later and not placeholder:
            placeholder = _DEFAULT_PLACEHOLDER

        # If category is decide_later, ensure the flag is set
        if category == QuestionCategory.DECIDE_LATER:
            is_decide_later = True
            if not placeholder:
                placeholder = _DEFAULT_PLACEHOLDER

        return ClassificationResult(
            original_question=original_question,
            category=category,
            reframed_question=reframed,
            reasoning=data.get("reasoning", ""),
            defer_to_dev=bool(data.get("defer_to_dev", False)),
            decide_later=is_decide_later,
            placeholder_response=placeholder,
        )
